- src/ingest-pipeline/schemata/dataset_metadata_schema.yml
Missed one in the previous merge
> Stray tweak to a still-unused schema file.

- src/ingest-pipeline/md/data_collection_types/__init__.py
- src/ingest-pipeline/md/data_collection_types/metadatatsv_data_collection.py
- src/ingest-pipeline/md/data_collection_types/rnaseq_10x_data_collection.py
Added a simple data collection type for a single -metadata.tsv alone, for developer use
> Added a simple DataCollectionType for metadata.tsv alone

- docker/docker-compose.localhost.yml
- src/ingest-pipeline/airflow/dags/salmon_rnaseq_10x.py
- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/airflow/plugins/hubmap_api/endpoint.py
- src/ingest-pipeline/instance/app.cfg.example
- src/ingest-pipeline/md/data_collection_types/akoya_codex_data_collection.py
- src/ingest-pipeline/md/data_collection_types/rnaseq_10x_data_collection.py
- src/ingest-pipeline/md/data_collection_types/stanford_codex_data_collection.py
Among other things, this includes the files_info_alt_path mechanism.
> Scratch from config 202005

- .gitmodules
- docker/docker-compose.localhost.yml
- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/airflow/plugins/hubmap_api/endpoint.py
- src/ingest-pipeline/md/data_collection_types/generic_metadatatsv_data_collection.py
- src/ingest-pipeline/md/data_file_types/metadatatsv_metadata_file.py
- src/ingest-pipeline/misc/systemd/airflow-dev
- src/ingest-pipeline/misc/tools/regenerate_venv.sh
- src/ingest-pipeline/requirements.txt
Implement consistency testing of fields of metadata.tsv which can be checked via uuid-api
> Welling consistency 202006

- src/ingest-pipeline/airflow/dags/sc_atac_seq_snare.py
- src/ingest-pipeline/airflow/dags/workflow_map.yml
I'm sure there are a lot of omissions in this -- I don't have a good handle on everything required to add a new data type along with this DAG. This seems ready to make a PR and ask for feedback though.
> Add scATAC-seq DAG

- src/ingest-pipeline/airflow/dags/bulk_atacseq.py
- src/ingest-pipeline/airflow/dags/codex_cytokit.py
- src/ingest-pipeline/airflow/dags/ometiff_pyramid.py
- src/ingest-pipeline/airflow/dags/salmon_rnaseq_10x.py
- src/ingest-pipeline/airflow/dags/salmon_rnaseq_bulk.py
- src/ingest-pipeline/airflow/dags/salmon_rnaseq_sciseq.py
- src/ingest-pipeline/airflow/dags/salmon_rnaseq_snareseq.py
- src/ingest-pipeline/airflow/dags/sc_atac_seq_sci.py
- src/ingest-pipeline/airflow/dags/sc_atac_seq_snare.py
- src/ingest-pipeline/airflow/dags/utils.py
Not very invasive or large changes, but touches every DAG that runs `cwltool`, so not without risk.
> Consolidate cwltool command-line initialization

- .gitmodules
The new submodule is currently unreferenced; it requires a new DAG that doesn't yet exist.
> Revert ome-tiff-pyramid submodule to v1.2, add ome-tiff-pyramid-ims submodule

- src/ingest-pipeline/airflow/dags/bulk_atacseq.py
> Bulk ATAC-seq: support multiple input directories

- src/ingest-pipeline/airflow/dags/launch_multi_analysis.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/airflow/dags/workflow_map.yml
Adds a DAG called 'launch_multi_analysis' which is intended to be manually triggered with a manually-entered JSON string containing run information.
> Welling multi parent 202008

- src/ingest-pipeline/airflow/dags/codex_cytokit.py
This replaces the current SPRM pipeline of sprm-to-json with https://github.com/hubmapconsortium/portal-containers/pull/58.  Now all outputs will be AnnData and any future SPRM outputs should be run against this container.   Should I remove the updates to the other two repos or are those OK?  Is there anything else that needs to be done for getting this into this repo?
> SPRM-to-AnnData Update for HuBMAP UI

- src/ingest-pipeline/misc/tools/new_dataset_survey.py
- src/ingest-pipeline/misc/tools/survey.py
This just makes some enhancements to misc/tools/survey.py and adds new_dataset_survey.py to the same directory.  survey.py is used to create a spreadsheet of info on dataset status based on information in a metadata.tsv file by querying entity-api and search-api .  new_dataset_survey.py scans through a provided list of status=New datasets using the same methods.
> Add misc/tools/new_dataset_survey.py

- .gitmodules
- src/ingest-pipeline/airflow/dags/salmon_rnaseq.py
Forgot that @mruffalo was making the `hubmap_ui` directory so need to merge https://github.com/hubmapconsortium/portal-containers/pull/61 first and re-update.
> (RNA) Sequencing Update for Portal Containers

- src/ingest-pipeline/airflow/dags/salmon_rnaseq.py
- src/ingest-pipeline/airflow/dags/workflow_map.yml
Make absolutely sure that these assays are processed as such, using both intronic and exonic counts when appropriate.
> Improve explicit support for snRNA-seq

- src/ingest-pipeline/airflow/dags/sc_atac_seq.py
> Fix sc_atac_seq workflow in DAG

- src/ingest-pipeline/requirements.txt
- What I Did
-    Added a hard sqlalchemy version to requirments.txt
- Why I Did It
-    To address issue #252 
- Revision
-    Patch
> General: add a hard sqlalchemy requirement

- src/ingest-pipeline/misc/tools/new_dataset_survey.py
Straggler mods from previous merge?
> Avoid duplicate rows when merging in new_dataset_survey.py

- src/ingest-pipeline/airflow/dags/utils.py
Should be `extras/thumbnail.jpg` instead of `extra/thumbnail.jpg`
> Fix incorrect thumbnail path

- src/ingest-pipeline/airflow/dags/celldive_deepcell.py
This PR contains the code to add the metadata data_path to the data directory, plus some pylint cleanup.
> Fixes to celldive_deepcell DAG found in testing, plus some pylint

- src/ingest-pipeline/misc/tools/new_upload_survey.py
Adds a simple utility to generate a .tsv file of Uploads, analogous to the table of Datasets produced by new_dataset_survey.py
> New misc tool for maintaining a spreadsheet of Uploads

- src/ingest-pipeline/airflow/plugins/globus_auth/globus_auth.py
- src/ingest-pipeline/airflow/plugins/hubmap_api/endpoint.py
Changes made as per @shirey request.
> Jpuerto psc/token change

- src/ingest-pipeline/airflow/dags/generate_usage_report.py
This PR adds some logging output to the generate_usage_report DAG, and adds code to clear the scratch directory if it contains files at the beginning of the operation.  This condition can occur if the report generation step is retried under Airflow, causing an already-used scratch directory to be reused.
I believe that problem was the actual cause of the errors I saw in operation on PROD, but the added diagnostics will help in any case.
> Added logging output to generate_usage_report. From PROD hotfix.

- src/ingest-pipeline/misc/tools/extract_for_review.py
Data provider requested an update since the information is misleading for them without the correct naming. That name wasn't unified on a single item on the entity-api response.
> Update on extract_for_review

- src/ingest-pipeline/misc/tools/extract_for_review.py
Updated script to show the information from the parent dataset on derived when switched from lab_dataset_id to provider_info at ingest time
> Update utility to extract tabular data to aid TMCs reviewing datasets for publication

- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/validate_upload.py
- src/ingest-pipeline/airflow/dags/validation_test.py
Provide 'info' keyword parameter dict to ErrorReport constructor
> ingest-validation-tools ErrorReport now takes an 'info' argument

- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_test.sh
- src/ingest-pipeline/misc/tools/airflow_startup_scripts/source_to_start_TEST_GPU.sh
This PR adds several misc/tools/airflow_environments scripts created during testing of the previous batch in the context of release_1.9 on TEST.
> Importing updated config scripts developed during release_1.9 testing

- src/ingest-pipeline/misc/tools/new_dataset_survey.py
- src/ingest-pipeline/misc/tools/survey.py
- src/ingest-pipeline/requirements.txt
Refactoring of new_dataset_survey to connect directly to the google docs spreadsheet, and a workaround for bogus datasets with no parent.
> Refactoring of new_dataset_survey to connect directly to google docs

- src/ingest-pipeline/misc/systemd/airflow-flower.service
- src/ingest-pipeline/misc/systemd/airflow-worker.service
- src/ingest-pipeline/misc/systemd/airflow-worker@.service
Airflow 2 requires some changes to the command lines used in systemd configs.
> Update systemd configs for Airflow 2

- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_stage.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_stage.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_ubuntu_22.04_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_ubuntu_22.04_test.sh
Updated all the environment scripts to make use of Conda, also added one for stage
> Updated config scripts to make use of conda

- src/ingest-pipeline/airflow/dags/launch_multi_analysis.py
- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/trigger_downstream_processing.py
- src/ingest-pipeline/airflow/plugins/hubmap_operators/flex_multi_dag_run.py
- src/ingest-pipeline/airflow/plugins/hubmap_operators/flex_multi_dag_run.py.af1
Updated the class to support Airflow 2 DAG triggering.
> Bugfix downstream dag creation not respecting max_active_run parameter

- src/ingest-pipeline/airflow/dags/launch_multi_analysis.py
Bugfix on launch multi analysis dag after updated version of the FlexMultiDagRun class for Airflow 2
> Bugfix launch multi analysis

- src/ingest-pipeline/airflow/dags/diagnostics/diagnostic_plugin.py
- src/ingest-pipeline/airflow/dags/diagnostics/plugins/illegal_argument_plugin.py
- src/ingest-pipeline/airflow/dags/diagnostics/plugins/io_errors_plugin.py
[Issue NIHDEV-157](https://pscdevteam.atlassian.net/jira/software/projects/NIHDEV/boards/1?selectedIssue=NIHDEV-157)
This plugin attempts to locate IllegalArgumentExceptions and determine whether they are in a relevant docker container. Path branches to include generic IllegalArgumentExceptions for thoroughness. This PR also includes some abstraction of logic into a parent RegexDiagnosticPlugin and subsequent revision to the IOError plugin.
As I am testing integrating linting into PSC HuBMAP repos, this repo includes changes to quotations and line breaks as well. Apologies for the noise.
> plugin for catching IllegalArgument errors in specific docker containers

- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9_test.sh
- Bugfix on the new send msg function that updates entity metadata for different scenarios.
- New RHEL 9 environment scripts.
> Bugfix send msg function + New RHEL 9 environment variables

- src/ingest-pipeline/airflow/plugins/hubmap_api/endpoint.py
Removed unnecessary reload of dags to optimize response time.
> Updates on API endpoint

- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_cmudev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_pittdev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_stage.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_cmudev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_pittdev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_centos_8_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_cmudev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_pittdev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9.0_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9.0_test.sh
Updated scripts to use the new global environment variable for python version.
Resync on CWL/SPRM to latest version.
> Updated scripts and bugfix

- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/requirements.txt
Bugfix status update for newly created derived dataset processed correctly when indexing fails.
Updating Airflow to the latest version.
Bump validation-tools 650f971
Bump validation-tests eb3986f
> Bugfix status update

- src/ingest-pipeline/misc/tools/airflow_environments/env_dev.sh
- src/ingest-pipeline/requirements.txt
Update to support new infrastructure.
> Environment scripts update

- .gitmodules
ReSync of the submodule due to inconsistencies.
> Bugfix cwl create-vis-symlink-archive submodule

- .gitmodules
Removing submodule ometiff-pyramid-ims which was replaced by ometiff-pyramid
> Removing old submodule

- src/ingest-pipeline/misc/tools/survey.py
Adding missing Publication assignment when building the Entity object.
> Bugfix Publication survey

- src/ingest-pipeline/airflow/dags/utils.py
Updated server to make the call to be entity-api sin ingest-api does not have this endpoint anymore.
> Bugfix error callback call

- src/ingest-pipeline/md/data_collection_types/generic_metadatatsv_data_collection.py
Added a message to clarify the origin of the assertion
> Added assertion message

- src/ingest-pipeline/misc/tools/split_and_create.py
Data providers can use boolean words on description column in metadata files that will affect processing.
> Bugfix reserved boolean word

- src/ingest-pipeline/misc/tools/split_and_create.py
New datasets created on reorganize DAG will get the Submitted status since they are already validated.
> Submitted status for split datasets from Upload

- src/ingest-pipeline/misc/tools/airflow_environments/env_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9.0_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9.0_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9.0_stage.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_9.0_test.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_stage.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_test.sh
Updated scripts for the new infrastructure, covering paths and env variables
> Updated script for new infrastructure

- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/validate_upload.py
- updating ingest_validation_tools_upload to include new optional args for CEDAR implementation in ingest-validation-tools
- bumping ingest-validation-tools
> Update to support changes to ingest-validation-tools

- src/ingest-pipeline/airflow/dags/reorganize_upload.py
- src/ingest-pipeline/misc/tools/split_and_create.py
Adding support for "extras" directory inside data folders on Uploads.
> Extras directory support on Upload data folder

- .flake8
- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/validate_upload.py
Bugfix IVT with new token naming
> Bugfix IVT calling

- src/ingest-pipeline/misc/tools/airflow_environments/env_dev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_pittdev.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_prod.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_stage.sh
- src/ingest-pipeline/misc/tools/airflow_environments/env_test.sh
> Bugfix url for UBKG

- src/ingest-pipeline/airflow/dags/extra_utils.py
- src/ingest-pipeline/airflow/dags/reorganize_multiassay.py
- src/ingest-pipeline/airflow/dags/reorganize_upload.py
- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/misc/tools/split_and_create.py
- src/ingest-pipeline/misc/tools/survey.py
Refactoring Reorganize Upload to support Soft / Multi Assay.
> Reorganize refactor

- src/ingest-pipeline/misc/tools/split_and_create.py
Bugfix response hint invalid type
> Bugfix response hint

- src/ingest-pipeline/airflow/dags/extra_utils.py
- src/ingest-pipeline/airflow/dags/reorganize_upload.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/misc/tools/split_and_create.py
- src/ingest-pipeline/misc/tools/survey.py
A couple of bugfixing items, and adding some extra validations to support previous metadata version.
> Bugfixing Reorganize upload

- src/ingest-pipeline/airflow/dags/validate_upload.py
Removing validation for old data_type field.
> Bugfix old data_type validation

- src/ingest-pipeline/airflow/dags/utils.py
Adding DAG information to send status and mitigate bad cache issue.
> Updating send_status

- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/validate_upload.py
app_context allows IVT to use different environmets for code stages.
> Adding app_context support for IVT

- src/ingest-pipeline/airflow/dags/launch_multi_analysis.py
Updating old reference to data_types for the new field dataset_type on launch_multi_analysis DAG.
> Bugfix old reference to data_types

- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
Adding ingest validation tools git hash to the dag_provenance_list metadata field to allow teams to track file indexing and other post-processing actions.
> Adding IVT git hash to dag_provenance_list

- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/validate_upload.py
Added Ingest API URL to app_context, updated IVT commit.
> Update to support change in IVT

- src/ingest-pipeline/airflow/dags/multiassay_component_metadata.py
- src/ingest-pipeline/airflow/dags/resource_map.yml
Adding resource map configuration for new rebuilding metadata DAGs so it can be configured to allow more processing power to it.
> Adding rebuilding metadata resource mapping

- src/ingest-pipeline/airflow/dags/resource_map.yml
- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/airflow/dags/workflow_map.yml
- src/ingest-pipeline/md/data_collection_types/akoya_codex_data_collection.py
- src/ingest-pipeline/md/data_collection_types/devtest_data_collection.py
- src/ingest-pipeline/md/data_collection_types/generic_metadatatsv_data_collection.py
- src/ingest-pipeline/md/data_collection_types/ims_data_collection.py
- src/ingest-pipeline/md/data_collection_types/metadatatsv_data_collection.py
- src/ingest-pipeline/md/data_collection_types/rnaseq_10x_data_collection.py
- src/ingest-pipeline/md/data_collection_types/stanford_codex_data_collection.py
- src/ingest-pipeline/misc/tools/split_and_create.py
- src/ingest-pipeline/requirements.txt
Syncing some bugfixes found in SenNet.
Adding missing parametrization definitions for new pipelines.
> SenNet syncing and parametrization updates

- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/plugins/hubmap_api/endpoint.py
- src/ingest-pipeline/requirements.txt
New endpoint for bulk submission from UI.
> New endpoint for bulk submission

- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
Removing extra_paramenter duplicated by different PRs
> Removing duplicated parameter

- src/ingest-pipeline/airflow/dags/bulk_process.py
- src/ingest-pipeline/airflow/dags/reorganize_upload.py
New DAG based on launch multi analysis structure but instead of linking the uuid_lists as parents for a unique processed derived dataset it uses it as a list of uuids to process as individual datasets.
> New DAG for bulk processing

- src/ingest-pipeline/airflow/dags/utils.py
Updating the limit since we no longer send this request to ingest-api.
> Updating MAX_IN_LINE_FILES limit 

- src/ingest-pipeline/airflow/dags/celldive_deepcell.py
- src/ingest-pipeline/airflow/dags/resource_map.yml
Updated SPRM step with processes flag to it can multithread.
Updated resource_map with a good thread count for CellDIVE and removed duplicated entries.
> Updated CellDIVE params

- src/ingest-pipeline/airflow/dags/resource_map.yml
Removing unused entries.
Updated ometiff to current pipelines.
Updated default lanes
> Updated resource_map

- src/ingest-pipeline/md/data_collection_types/multiassay_metadatatsv_data_collection.py
Adding missing token for metadata extraction calls to assayclassifier
> Bug fix new token requirement

- src/ingest-pipeline/airflow/dags/reorganize_upload.py
Adding token to reorganization script environment.
> Bugfix missing token

- src/ingest-pipeline/airflow/dags/launch_multi_analysis.py
Bump ingest-validation-tools v1.0.1
> Bump ingest-validation-tools v1.0.1

- src/ingest-pipeline/airflow/dags/visium.py
- src/ingest-pipeline/airflow/dags/workflow_map.yml
Syncing SenNet tested bugfix for the missing parameter.
> Syncing bugfix for organism paramenter in visium pipeline

- src/ingest-pipeline/airflow/dags/multiome.py
Exposing organism as parameter of multiome pipeline
> Bump multiome-rna-atac-pipeline to v1.1.8

- src/ingest-pipeline/misc/tools/auto_deploy.sh
Enhancing auto_deploy script to take information for the environment from the sysconfig files and pass that downstream to scripts that needs them.
> auto_deploy enhancement

- src/ingest-pipeline/airflow/dags/bulk_atacseq.py
- src/ingest-pipeline/airflow/dags/extra_utils.py
- src/ingest-pipeline/airflow/dags/reorganize_upload.py
- src/ingest-pipeline/airflow/dags/resource_map.yml
- src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
- src/ingest-pipeline/airflow/dags/validate_upload.py
- src/ingest-pipeline/md/data_collection_types/__init__.py
- src/ingest-pipeline/md/data_collection_types/epic_metadata_data_collection.py
- src/ingest-pipeline/md/data_file_types/__init__.py
- src/ingest-pipeline/md/data_file_types/metadatatsv_metadata_file.py
- src/ingest-pipeline/md/data_file_types/ome_tiff_metadata_file.py
- src/ingest-pipeline/misc/tools/split_and_create.py
- src/ingest-pipeline/misc/tools/survey.py
Some adjustments need to happen on the reorganization steps to support EPICs
> EPICs reorganization

- src/ingest-pipeline/airflow/dags/utils.py
Bugfix missing multiome_snareseq assay for re-annotations
> Bugfix missing multiome_snareseq assay for re-annotations

- src/ingest-pipeline/airflow/dags/utils.py
> Bugix datatype error

- src/ingest-pipeline/airflow/dags/utils.py
Bugfix missing data path to source annotations for datasets in QA
> Bugfix missing data path to source annotations for datasets in QA

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
- src/ingest-pipeline/airflow/dags/utils.py
The matrix parameter should be dynamic based on previous run, now that multiome exists.
> Bugfix static matrix parameter to dynamic

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
- src/ingest-pipeline/airflow/dags/utils.py
Bugfix wrong secondary_analysys for multiome
> Bugfix wrong secondary_analysys for multiome

- src/ingest-pipeline/airflow/dags/validate_upload.py
Integrate error counting into validate_upload
> Error counts

- src/ingest-pipeline/requirements.txt
> Bump azimuth-annotate

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/misc/tools/auto_deploy.sh
Updating the DAG to support multiome variants in the process.
> Re-Annotation DAG update to support multiome UI processing

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
> Bugfix typo in step reference

- src/ingest-pipeline/airflow/dags/pas_ftu_segmentation.py
> Bugfix: wrong task_id call

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
- src/ingest-pipeline/airflow/dags/utils.py
Bugfix wrong trigger rule for new forks
> Bugfix wrong trigger rule for new forks

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
Bugfix: TyPo on new attribute to move data step
> Bugfix: TyPo on new attribute to move data step

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
Bugfix: Wrong cwl_workflow to calculate files for multiome reannotation
> Bugfix: Wrong cwl_workflow to calculate files for multiome reannotation

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
New approach to generate metadata for multiome datasets after re-annotation
> Bugfix: cwlworkflow calculations for multiome datasets

- src/ingest-pipeline/airflow/dags/utils.py
Bugfix: dag provenance recalculation for multiome
> Bugfix: dag provenance recalculation for multiome

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
- src/ingest-pipeline/airflow/plugins/hubmap_operators/common_operators.py
Updating the DAG with corrected workflow
> Azimuth re-annotation DAG update

- src/ingest-pipeline/airflow/dags/codex_cytokit.py
- src/ingest-pipeline/airflow/dags/mibi_deepcell.py
- src/ingest-pipeline/airflow/dags/ometiff_pyramid.py
- src/ingest-pipeline/airflow/dags/ometiff_pyramid_ims.py
- src/ingest-pipeline/airflow/dags/pas_ftu_segmentation.py
- src/ingest-pipeline/airflow/dags/phenocycler_deepcell.py
- src/ingest-pipeline/airflow/dags/salmon_rnaseq_bulk.py
- src/ingest-pipeline/airflow/dags/visium.py
Bump IVT v0.0.29
Bump IVTests v1.1.1
> Bump IVT IVTests

- src/ingest-pipeline/airflow/dags/kaggle_2_segmentation.py
- src/ingest-pipeline/misc/tools/airflow_environments/env_cmudev.sh
Bump portal-containers.
Addedd new steps for extracting metadata to correctly visualize the results.
> Bump portal-containers v0.0.44

- src/ingest-pipeline/airflow/dags/transformations/tsv_to_mudata.py
Reads TSV format, adds `image_dimension` to JSON metadata
> Bump epic-obj-csv-to-mudata submodule to v0.3

- .gitmodules
- src/ingest-pipeline/airflow/dags/bulk_atacseq.py
- src/ingest-pipeline/airflow/dags/bulk_process.py
- src/ingest-pipeline/airflow/dags/celldive_deepcell.py
- src/ingest-pipeline/airflow/dags/codex_cytokit.py
- src/ingest-pipeline/airflow/dags/extra_utils.py
- src/ingest-pipeline/airflow/dags/gen_pub_ancillary.py
- src/ingest-pipeline/airflow/dags/geomx.py
- src/ingest-pipeline/airflow/dags/kaggle_2_segmentation.py
- src/ingest-pipeline/airflow/dags/launch_multi_analysis.py
- src/ingest-pipeline/airflow/dags/mibi_deepcell.py
- src/ingest-pipeline/airflow/dags/multiome.py
- src/ingest-pipeline/airflow/dags/ometiff_pyramid.py
- src/ingest-pipeline/airflow/dags/ometiff_pyramid_ims.py
- src/ingest-pipeline/airflow/dags/pas_ftu_segmentation.py
- src/ingest-pipeline/airflow/dags/phenocycler_deepcell.py
- src/ingest-pipeline/airflow/dags/reorganize_upload.py
- src/ingest-pipeline/airflow/dags/salmon_rnaseq.py
- src/ingest-pipeline/airflow/dags/salmon_rnaseq_bulk.py
- src/ingest-pipeline/airflow/dags/sc_atac_seq.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/airflow/dags/visium.py
- src/ingest-pipeline/airflow/dags/visium_probes.py
- src/ingest-pipeline/airflow/plugins/hubmap_api/endpoint.py
- src/ingest-pipeline/instance/app.cfg.example
- src/ingest-pipeline/requirements.txt
- src/ingest-pipeline/schemata/launch_multi_metadata_schema.yml
* A new processed dataset will only be created after a successful pipeline run.
* Support for containers to be created on the fly.
* Bump CODEX v2.7.1.
* New CODEX cell types DeepCellTypes and RIBCA.
> New flow: creating datasets just after sucessful runs

- src/ingest-pipeline/airflow/dags/codex_cytokit.py
- src/ingest-pipeline/airflow/dags/geomx.py
- src/ingest-pipeline/airflow/dags/reorganize_multiassay.py
- src/ingest-pipeline/airflow/dags/status_change/status_manager.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/airflow/plugins/hubmap_operators/common_operators.py
Updating utils and StatusChanger to avoid updating status on components.
Small bugfix on StatusChange to better handle of no status updates.
> Bugfix metadata update on components

- src/ingest-pipeline/airflow/dags/azimuth_annotations.py
- src/ingest-pipeline/airflow/dags/bulk_process.py
- src/ingest-pipeline/airflow/dags/utils.py
- src/ingest-pipeline/airflow/plugins/hubmap_operators/common_operators.py
- src/ingest-pipeline/requirements.txt
* Azimuth bugfix for new cwl workflow.
* Adding trigger_rule control for JoinOperator for azimuth annotation split path.
* Bugfix for bulk_process, so it can create the correct previous_version_uuid.
* Bugfix for dataset set status when there is no dataset created.
* Adding new requirement for fresh installs.
> Bugfixes: Azimuth, New data model, Bulk process

- src/ingest-pipeline/misc/tools/set_standard_protections.py
Updating the call to add the permission setting.
> Bugfix permission script call

- src/ingest-pipeline/airflow/dags/multiassay_component_metadata.py
- src/ingest-pipeline/airflow/dags/rebuild_primary_dataset_metadata.py
- src/ingest-pipeline/airflow/dags/rebuild_processed_dataset_metadata.py
- src/ingest-pipeline/schemata/rebuild_metadata_schema.yml
This PR adds a new YAML schema and updates DAGs to use this new YAML schema.
> fix: new schema file for rebuild metadata
