hubmapconsortium/ingest-pipeline

src/ingest-pipeline/airflow/dags/codex_cytokit.py
src/ingest-pipeline/airflow/dags/devtest_step2.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_10x.py
src/ingest-pipeline/airflow/dags/utils.py
src/ingest-pipeline/schemata/file_info_schema.json
src/ingest-pipeline/schemata/file_info_schema.yml
src/ingest-pipeline/schemata/pipeline_file_manifest.json
src/ingest-pipeline/schemata/pipeline_file_manifest.yml

This PR implements filtering of the data files produced by analysis pipelines, leaving full results on disk but only including selected files in indexes and downstream steps (e.g. the portal UI).

Use pipeline output manifests, if present

---

src/ingest-pipeline/airflow/dags/utils.py

Found this while checking against schemas; this fix was only in a Git stash which happened to be what I tested against.

Hotfix: read correct ontology term from manifest

---

src/ingest-pipeline/airflow/dags/utils.py

This is more flexible, and still lets people match only at the start of a file path if desired, by prepending `^` to the regex patterns in a manifest.

Match pipeline manifest patterns with `re.search` instead

---

src/ingest-pipeline/airflow/dags/.airflowignore
src/ingest-pipeline/airflow/dags/bulk_atacseq.py
src/ingest-pipeline/airflow/dags/codex_cytokit.py
src/ingest-pipeline/airflow/dags/devtest_step2.py
src/ingest-pipeline/airflow/dags/ingest_vanderbilt.py
src/ingest-pipeline/airflow/dags/mock_ingest_rnaseq_10x.py
src/ingest-pipeline/airflow/dags/mock_ingest_vanderbilt.py
src/ingest-pipeline/airflow/dags/ometiff_pyramid.py
src/ingest-pipeline/airflow/dags/reset_submission_to_new.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_10x.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_bulk.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_sciseq.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_snareseq.py
src/ingest-pipeline/airflow/dags/sc_atac_seq_sci.py
src/ingest-pipeline/airflow/dags/sc_atac_seq_snare.py
src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
src/ingest-pipeline/airflow/dags/utils.py
src/ingest-pipeline/airflow/plugins/hubmap_operators/common_operators.py

This avoids many deprecation warnings each time the dags are scanned, mainly by not sending 'provide_context=True' to BashOperators.
Also added the 'obsolete' subdir to dags/.gitignore

Avoid many DeprecationWarnings from DAGs.

---

src/ingest-pipeline/airflow/dags/ometiff_pyramid_ims.py

Version 1.3 of the `ome-tiff-pyramid` pipeline exposes downsample type as an option to the user. Update the `ome-tiff-pyramid-ims` submodule to use this version and set `DOWNSAMPLE_TYPE = 'CUBIC'` in the `ometiff_pyramid_ims` DAG.
This should allow for experiments with other downsample types via local modifications of the DAG.

Update ome-tiff-pyramid for IMS: allow arbitrary downsampling types from the DAG

---

src/ingest-pipeline/airflow/dags/codex_cytokit.py

I introduced a bug in 2d1e5b4ead70ed8f28689d53a8eae91610c132ad, due to bit rot in rebasing that commit too many times.
Fix trying to use a `str` path like a `Path` object.

codex_cytokit DAG: fix build_cwltool_cmd2

---

src/ingest-pipeline/airflow/dags/bulk_atacseq.py
src/ingest-pipeline/airflow/dags/codex_cytokit.py
src/ingest-pipeline/airflow/dags/devtest_step2.py
src/ingest-pipeline/airflow/dags/ometiff_pyramid.py
src/ingest-pipeline/airflow/dags/ometiff_pyramid_ims.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_10x.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_bulk.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_sciseq.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq_snareseq.py
src/ingest-pipeline/airflow/dags/sc_atac_seq_sci.py
src/ingest-pipeline/airflow/dags/sc_atac_seq_sn.py
src/ingest-pipeline/airflow/dags/sc_atac_seq_snare.py
src/ingest-pipeline/airflow/dags/utils.py

This is much nicer than wrapping every call to this function in `Path(...)` -- I had done the latter to avoid breaking things with other usage of `get_tmp_dir_path` that I wasn't aware of.

Return Path objects from utils.get_tmp_dir_path

---

src/ingest-pipeline/airflow/dags/launch_multi_analysis.py
src/ingest-pipeline/schemata/launch_multi_metadata_schema.yml

Multi-dataset analyses are currently started manually, by triggering the launch_multi_analysis DAG with a JSON string specifying the input datasets and the analysis.  This PR adds schema testing to the dag so that errors in that JSON string can produce sensible messages.

Add a schema to launch_multi_analysis DAG

---

src/ingest-pipeline/airflow/dags/utils.py

This PR addresses issue #328  with the following workflow:
- ingest-pipeline looks for the `extra/thumbnail.jpg` for a given dataset, and send back the absolute file path if found
- ingest-pipeline makes a PUT call to ingest-api's `/datasets/status` endpoint with the metadata
- ingest-api looks for the `thumbnail_file_abs_path` field and handles the dataset update along with all other updated records via entity-api.
@jswelling I've deployed all the related changes from entity-api/gateway/ingest-api on STAGE and tested the subsequent handling without using Airflow. I'm not sure if the changes I made in this PR would work, so can you please review and if all good, can you merge and deploy to STAGE so we can try it out?

Register thumbnail image

---

src/ingest-pipeline/airflow/dags/codex_cytokit.py

Updates the output directory structure to match CellDIVE processing, with corresponding changes to the `codex_cytokit` DAG.

Bump codex-pipeline to v2.3

---

src/ingest-pipeline/misc/tools/replace_metadata_assay_type.sh

A convenience script for those times when it is necessary to update the assay_type column of metadata.tsv scripts.

Added misc/tools/replace_metadata_assay_type.sh

---

src/ingest-pipeline/airflow/dags/reorganize_upload.py
src/ingest-pipeline/misc/tools/split_and_create.py

This PR restructures split_and_create.py to deal with Uploads that contain more than one metadata.tsv file.  The
reorganize_upload.py DAG is also modified, to account for those changes.
This has been tested on DEV with a clone of a real-world 2-metadata-file Upload.

Modify split_and_create to support multiple metadata.tsv files

---

src/ingest-pipeline/airflow/plugins/hubmap_api/endpoint.py

This PR substitutes the 'permanent token' for the token of the UI user when initiating Airflow runs via the Airflow plug-in endpoint.

Always use permanent tok when an airflow workflow is triggered. WIP.

---

src/ingest-pipeline/airflow/dags/celldive_deepcell.py

Well, technically for all data types processed by SPRM, but behavior for other assays is unchanged. This version of SPRM:
* Adds a mechanism to specify different options files ("presets") that are included with the software package and baked into the Docker image
* Adjusts two different tSNE parameters in the new `options-celldive.txt`
The update to the CellDIVE DAG sets the new `--options_preset` workflow option to `celldive`.

SPRM v1.0.8.2 for CellDIVE

---

src/ingest-pipeline/misc/tools/sterilize_fastq.py

This tool takes an existing FASTQ file and generates a similarly structured one, but with all identifiable information removed. Most alphanumeric characters are replaced with random substitutes, limited to what is necessary to keep the output from this sufficient to satisfy future input validators.

Sterilizer for FASTQ files

---

src/ingest-pipeline/misc/tools/sterilize_fastq.py

Simple argument to take a command-line-provided string to feed into random.seed().

Add --seed option to sterilizer to consistify random subselection

---

src/ingest-pipeline/requirements.txt

This adds fastq-utils to requirements.txt via github.  Since this is now a requirement of ingest-validation-tests, one of our submodules, it must be a requirement here as well.

Add fastq-utils to requirements.txt

---

src/ingest-pipeline/requirements.txt

The python version on production HIVE is currently stuck at 3.6 for OS reasons.  dataclasses becomes a standard module at 3.7, and it is needed by fastq_utils .  This PR adds dataclasses to requirements.txt .

fastq_utils requires dataclasses, not present in python 3.6

---

src/ingest-pipeline/airflow/dags/resource_map.yml

This change shifts the segmentation tasks of the celldive_deepcell pipeline to GPU hosts, which they need in order to run.

The *segmentation tasks for celldive_deepcell need to run on a gpu

---

src/ingest-pipeline/misc/tools/new_dataset_survey.py
src/ingest-pipeline/misc/tools/survey.py

This PR causes survey.py to get the list of uuids needed for new_dataset_survey from a newly deployed endpoint on entity-api, rather than from a spreadsheet explicitly downloaded from Neo4J.  This significantly simplifies the process of generating updates to the Unpublished Datasets spreadsheet.

Modified survey.py and new_dataset_survey.py to get datasets from entity-api

---

src/ingest-pipeline/misc/tools/regenerate_venv.sh
src/ingest-pipeline/misc/tools/test_create_dataset.py

The only breaking change was the name change of the master branch, which becomes main.  get_globus_groups_info was referenced, but the data never actually got used in the current code, so that could just be deleted.

Trivial changes to address a refactor of hubmap-commons

---

src/ingest-pipeline/misc/tools/schema_tester.py

This tool checks .yml or .json files against the schemata in the src/ingest-pipeline/schemata directory , using the jsonschema support routines in the commons library.

Add a simple command line tool to test files against a schema

---

src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_prod.sh
src/ingest-pipeline/misc/tools/airflow_environments/env_rhel_8.5_prod.sh

These are the PROD equivalents of existing config scripts for DEV and TEST.  They were created on the fly during deployment and need to be merged back into the repo.

Add PROD env config files for CentOS 7 and RHEL 8.5

---

src/ingest-pipeline/misc/tools/airflow_environments/env_centos_7_dev.sh
src/ingest-pipeline/misc/tools/airflow_wrapper.sh
src/ingest-pipeline/misc/tools/regenerate_conda_env.sh
src/ingest-pipeline/misc/tools/source_platform_file.sh
src/ingest-pipeline/requirements.txt

This PR addresses the following:
* Add a conda equivalent of the script regenerate_venv.sh
* Put the conda environment in /opt/environments
* Some common code between regenerate_conda_env and airflow_wrapper is moved to a separate script
Testing was performed under Airflow2 on DEV under both python3.6 and python3.9

Script to regenerate conda environment and associated issues

---

src/ingest-pipeline/airflow/dags/diagnostics/diagnostic_plugin.py

Base class DiagnosticResult.problem_found() was returning False when error strings were present.  Should have been True.  This PR fixes that error.

Fix an error in a base class method introduced in welling/diagnostics_dag

---

src/ingest-pipeline/airflow/dags/diagnostics/plugins/find_errors_plugin.py

This PR contains a plugin for the diagnose_failure DAG. This plugin uses regex to search for error strings and logs the lines with errors from session.log.
Note 1: The find_errors_plugin currently contains an override of FindErrorsDiagnosticResult.problem_found that may be unnecessary pending potential changes to parent class.
Note 2: I will name my branch better next time!

Plugin to find error strings in session.log

---

src/ingest-pipeline/airflow/dags/diagnostics/plugins/find_errors_plugin.py
src/ingest-pipeline/airflow/dags/diagnostics/plugins/io_errors_plugin.py

This plugin parses session.log files to find lines containing BOTH the string "OSError" and "Input/output error" sequentially (case insensitive due to specificity of pattern). It then prints an error message. It has been tested on DEV.
Its functionality is otherwise identical to ErrorDiagnosticsPlugin, suggesting a potential later refactor.

Diagnose i/o errors

---

src/ingest-pipeline/airflow/dags/utils.py

This PR adds the environment variable 
```
_JAVA_OPTIONS=-XX:ActiveProcessorCount=2
```
to all spawned CWL steps, which has the effect of making any java process spawned from that level think there are only 2 cores on its machine.  Since parallelism based on the threads= value is usually handled above the level of calls based on java (like bioformats tools), this gives about the right level of parallelism.
Another option would be
```
_JAVA_OPTIONS=-XX:ParallelGCThreads=2
```
which would only limit the GC threads.  This still allows other tasks (like actual work) to spawn as many threads as there are actual cores on the host, which might get more done but does allow some thread explosion.
Yet another option would be to set -XX:ActiveProcessorCount to the value of the threads= resource, but …

Add opt limiting all java threads to get_cwltool_base_cmd

---

src/ingest-pipeline/misc/tools/airflow_startup_scripts/source_to_start_DEV_GPU.sh
src/ingest-pipeline/misc/tools/airflow_startup_scripts/source_to_start_PROD_EM.sh
src/ingest-pipeline/misc/tools/airflow_startup_scripts/source_to_start_PROD_GPU.sh
src/ingest-pipeline/misc/tools/airflow_startup_scripts/source_to_start_TEST_GPU.sh

This PR changes the Airflow command 'worker' to 'celery worker' and the operand --celery_hostname to -H

Update airflow_startup_scripts for Airflow 2

---

src/ingest-pipeline/airflow/dags/catch_pipeline_errors.py
src/ingest-pipeline/airflow/dags/error_catching/failure_callback.py
src/ingest-pipeline/airflow/dags/error_catching/validate_upload_failure_callback.py
src/ingest-pipeline/airflow/dags/validate_upload.py

I'd love feedback on the base class (catch_pipeline_errors.py) and the subclass implementation in validate_upload.py.
Notes:
- The base FailureCallback class can be set as the callback method on a DAG to catch errors in the running DAG and send a notification to the internal email recipients set on the base class (likely data curators). It does not always need to be subclassed.
- However, in order to catch specific errors and send emails to data providers, FailureCallback must be subclassed.
- The ValidateUploadFailure subclass of FailureCallback is necessary in order to send emails when the validate_upload DAG succeeds but sub-processes determine the upload to be Invalid. Without this subclass, no notifications would be sent at all despite the upload entering an invalid state.
- …

Pipeline error catching

---

src/ingest-pipeline/airflow/dags/validate_upload.py
src/ingest-pipeline/airflow/dags/workflow_map.yml

Updated flow to clear/blank validation_message after a successful validation which makes the message outdated/useless on the upload/dataset.

Blank validation_message on successful validation

---

src/ingest-pipeline/airflow/dags/salmon_rnaseq.py

This debug output is from the CWL tool runner, not our pipelines or analysis code, and relates to how input/output files are mapped between workflow steps. This information is really only useful when *writing* CWL workflows, not when diagnosing pipeline failures, and dramatically bloat the log file contents, making it more difficult to find useful information about any particular failure.

salmon_rnaseq DAGs: remove --debug from cwltool cmd

---

src/ingest-pipeline/airflow/dags/gen_pub_ancillary.py

This PR changes the nesting level of one of the tests performed on publication directories as their ancillary data is built.  I don't think the error actually could cause any good dataset to be rejected or bad dataset to be passed, but it wasn't the intended logic pattern.

Indentation error caused gen_pub_ancillary to do the right thing the wrong way

---

src/ingest-pipeline/requirements.txt

The submodule ingest-validation-tests requires the imagecodecs module now, so add imagecodecs to requirements.txt here.

Add imagecodecs to requirements.txt

---

src/ingest-pipeline/airflow/dags/celldive_deepcell.py
src/ingest-pipeline/airflow/dags/codex_cytokit.py
src/ingest-pipeline/airflow/dags/mibi_deepcell.py

Since there is at least one data path that has an apostrophe, expand_symlinks task needs to be updated to support it.

Bugfix apostrohpe in data path

---

.flake8
.gitignore

- updating .gitignore to be more useful
- @jpuerto-psc @sunset666 as a note here, I tend to think that we should commit the `airflow/instance` dir with `app.cfg` in .gitignore but `app.cfg.example` committed (assuming it can be updated to be current/helpful--I am happy to take a stab at that)
- UNLESS there's a way this would interfere with using GitLab to store secrets
- added flake8 config file

updating .gitignore to be more useful, added flake8 config

---

src/ingest-pipeline/airflow/dags/scan_and_begin_processing.py
src/ingest-pipeline/airflow/dags/validate_upload.py

Changed to support ingest-validation-tools

do not need cedar api key arg when instantiating upload

---

src/ingest-pipeline/airflow/dags/status_change/status_manager.py
src/ingest-pipeline/airflow/dags/utils.py

Adding header to the get_dataset_state function requesting no-cache and adding response information from entity-api to the logs to debug missing updates on status.

Adding log and new header

---

src/ingest-pipeline/airflow/dags/sc_atac_seq.py

This is to make sure that we are using the latest pipeline description moving forward.

DAGs: Change SnapATAC to ArchR for the pipeline shorthand.

---

.gitignore
src/ingest-pipeline/airflow/dags/status_change/failure_callback.py
src/ingest-pipeline/airflow/dags/status_change/status_manager.py
src/ingest-pipeline/airflow/dags/status_change/status_utils.py
src/ingest-pipeline/airflow/dags/status_change/tests/test_status_changer.py
src/ingest-pipeline/airflow/dags/utils.py
src/ingest-pipeline/airflow/dags/validate_upload.py
src/ingest-pipeline/misc/tools/split_and_create.py

This PR adds the ability to append to fields in Entity API rather than overwriting them. I've abstracted the field updating logic upward into a new class, EntityUpdater, and made StatusChanger a specialized subclass.
- `status_manager.py` - contains the updates to StatusChanger and the new EntityUpdater class.
- EntityUpdater will pass args off to StatusChanger if a status is passed to it.
- StatusChanger will pass args off to EntityUpdater if it is not passed a status or if the status in Entity API is the same (which avoids an error caused by a PUT request to update the status with the same value).
- Can specify which fields you want to overwrite vs. append to.
- If a field is in both lists, an exception is thrown.
- Can pass custom delimiters (although they would apply to all …

StatusChanger update to allow appending to existing metadata in Entity API

---

src/ingest-pipeline/airflow/dags/status_change/status_manager.py

Catching case in `StatusChanger.update` where status is None and there are no other fields to change. Previously this would throw an exception because this is a bad call to entity-api, now it should log that no call was made.

StatusChanger bugfix for None status

---

src/ingest-pipeline/airflow/dags/celldive_deepcell.py
src/ingest-pipeline/airflow/dags/codex_cytokit.py
src/ingest-pipeline/airflow/dags/mibi_deepcell.py
src/ingest-pipeline/airflow/dags/multiome.py
src/ingest-pipeline/airflow/dags/pas_ftu_segmentation.py
src/ingest-pipeline/airflow/dags/phenocycler_deepcell.py
src/ingest-pipeline/airflow/dags/salmon_rnaseq.py
src/ingest-pipeline/airflow/dags/utils.py
src/ingest-pipeline/airflow/dags/visium.py

Centralized parameter --relax-path-checks for cwlTool.
Bumping portal containers to support this parameter.

Centralized parameter relax-path-checks

---

src/ingest-pipeline/airflow/dags/workflow_map.yml

Bump salmon-rnaseq to v2.2.9 with organism support.
Bugfix for updated assay_type definition of bulkRNA (bulk-RNA)

Bump salmon-rnaseq v2.2.9

---

src/ingest-pipeline/airflow/dags/bulk_process.py

Bugfix: casting uuid as a list for downstream processing.

Bugfix: casting uuid as a list for downstream processing.

---

src/ingest-pipeline/airflow/dags/ometiff_pyramid.py
src/ingest-pipeline/airflow/dags/ometiff_pyramid_ims.py

This PR adds handling of the threads resource to the ome_tiff_pyramid and ome_tiff_pyramid_ims DAGs.  It turns out that is all that is necessary to enable more parallelism for those tasks.

Pass thread count to CWL

---

tests/unittest_runner.py

Trivial change- unittest_runner.py was reporting no errors but returning a non-zero return code.  This broke the newly added CI action.

fix unittest_runner return code

---

src/ingest-pipeline/airflow/dags/status_change/slack/base.py
src/ingest-pipeline/airflow/dags/status_change/slack_manager.py
src/ingest-pipeline/airflow/dags/status_change/status_manager.py
src/ingest-pipeline/airflow/dags/status_change/status_utils.py
tests/test_status_changer.py

- Moved Slack channels from `airflow_conf` to `status_utils.py`, no Airflow restart required to make adjustments
- Dedicated `slack_channels_testing` dict for use in non-prod environments
- Better error handling
- Handling case where channel is not found for a given status
- Very readily default to base channel
- Prevent known exceptions in message managers (i.e. instances of `EntityUpdateException`) from causing task failure in Airflow  **(this most directly addresses the issues raised most recently)**
- Tests (find channel by env, use default if channel not found)

Slack bugfix
